// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.8.0
// source: area_calculator/area_calculator.proto

package area_calculator

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type TriangleParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base   float64 `protobuf:"fixed64,1,opt,name=base,proto3" json:"base,omitempty"`
	Height float64 `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *TriangleParams) Reset() {
	*x = TriangleParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_area_calculator_area_calculator_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TriangleParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriangleParams) ProtoMessage() {}

func (x *TriangleParams) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_area_calculator_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriangleParams.ProtoReflect.Descriptor instead.
func (*TriangleParams) Descriptor() ([]byte, []int) {
	return file_area_calculator_area_calculator_proto_rawDescGZIP(), []int{0}
}

func (x *TriangleParams) GetBase() float64 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *TriangleParams) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type RectangleParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Width  float64 `protobuf:"fixed64,1,opt,name=width,proto3" json:"width,omitempty"`
	Height float64 `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *RectangleParams) Reset() {
	*x = RectangleParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_area_calculator_area_calculator_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RectangleParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RectangleParams) ProtoMessage() {}

func (x *RectangleParams) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_area_calculator_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RectangleParams.ProtoReflect.Descriptor instead.
func (*RectangleParams) Descriptor() ([]byte, []int) {
	return file_area_calculator_area_calculator_proto_rawDescGZIP(), []int{1}
}

func (x *RectangleParams) GetWidth() float64 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *RectangleParams) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type RhombusParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Base   float64 `protobuf:"fixed64,1,opt,name=base,proto3" json:"base,omitempty"`
	Height float64 `protobuf:"fixed64,2,opt,name=height,proto3" json:"height,omitempty"`
}

func (x *RhombusParams) Reset() {
	*x = RhombusParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_area_calculator_area_calculator_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RhombusParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RhombusParams) ProtoMessage() {}

func (x *RhombusParams) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_area_calculator_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RhombusParams.ProtoReflect.Descriptor instead.
func (*RhombusParams) Descriptor() ([]byte, []int) {
	return file_area_calculator_area_calculator_proto_rawDescGZIP(), []int{2}
}

func (x *RhombusParams) GetBase() float64 {
	if x != nil {
		return x.Base
	}
	return 0
}

func (x *RhombusParams) GetHeight() float64 {
	if x != nil {
		return x.Height
	}
	return 0
}

type SquareParams struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Length float64 `protobuf:"fixed64,1,opt,name=length,proto3" json:"length,omitempty"`
}

func (x *SquareParams) Reset() {
	*x = SquareParams{}
	if protoimpl.UnsafeEnabled {
		mi := &file_area_calculator_area_calculator_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SquareParams) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SquareParams) ProtoMessage() {}

func (x *SquareParams) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_area_calculator_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SquareParams.ProtoReflect.Descriptor instead.
func (*SquareParams) Descriptor() ([]byte, []int) {
	return file_area_calculator_area_calculator_proto_rawDescGZIP(), []int{3}
}

func (x *SquareParams) GetLength() float64 {
	if x != nil {
		return x.Length
	}
	return 0
}

type AreaReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Area float64 `protobuf:"fixed64,1,opt,name=area,proto3" json:"area,omitempty"`
}

func (x *AreaReply) Reset() {
	*x = AreaReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_area_calculator_area_calculator_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AreaReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AreaReply) ProtoMessage() {}

func (x *AreaReply) ProtoReflect() protoreflect.Message {
	mi := &file_area_calculator_area_calculator_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AreaReply.ProtoReflect.Descriptor instead.
func (*AreaReply) Descriptor() ([]byte, []int) {
	return file_area_calculator_area_calculator_proto_rawDescGZIP(), []int{4}
}

func (x *AreaReply) GetArea() float64 {
	if x != nil {
		return x.Area
	}
	return 0
}

var File_area_calculator_area_calculator_proto protoreflect.FileDescriptor

var file_area_calculator_area_calculator_proto_rawDesc = []byte{
	0x0a, 0x25, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x22, 0x3c, 0x0a, 0x0e, 0x54, 0x72, 0x69, 0x61,
	0x6e, 0x67, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61,
	0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x3f, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e,
	0x67, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x77, 0x69, 0x64,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x77, 0x69, 0x64, 0x74, 0x68, 0x12,
	0x16, 0x0a, 0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x06, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x22, 0x3b, 0x0a, 0x0d, 0x52, 0x68, 0x6f, 0x6d, 0x62,
	0x75, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x61, 0x73, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x62, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x68, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x22, 0x26, 0x0a, 0x0c, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x01, 0x52, 0x06, 0x6c, 0x65, 0x6e, 0x67, 0x74, 0x68, 0x22, 0x1f, 0x0a, 0x09,
	0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x65,
	0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x01, 0x52, 0x04, 0x61, 0x72, 0x65, 0x61, 0x32, 0xc8, 0x02,
	0x0a, 0x0e, 0x41, 0x72, 0x65, 0x61, 0x43, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72,
	0x12, 0x4d, 0x0a, 0x0c, 0x54, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x41, 0x72, 0x65, 0x61,
	0x12, 0x1f, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x54, 0x72, 0x69, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x1a, 0x1a, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61,
	0x74, 0x6f, 0x72, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12,
	0x4f, 0x0a, 0x0d, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x41, 0x72, 0x65, 0x61,
	0x12, 0x20, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74,
	0x6f, 0x72, 0x2e, 0x52, 0x65, 0x63, 0x74, 0x61, 0x6e, 0x67, 0x6c, 0x65, 0x50, 0x61, 0x72, 0x61,
	0x6d, 0x73, 0x1a, 0x1a, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c,
	0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00,
	0x12, 0x4b, 0x0a, 0x0b, 0x52, 0x68, 0x6f, 0x6d, 0x62, 0x75, 0x73, 0x41, 0x72, 0x65, 0x61, 0x12,
	0x1e, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x52, 0x68, 0x6f, 0x6d, 0x62, 0x75, 0x73, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a,
	0x1a, 0x2e, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f,
	0x72, 0x2e, 0x41, 0x72, 0x65, 0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x12, 0x49, 0x0a,
	0x0a, 0x53, 0x71, 0x75, 0x61, 0x72, 0x65, 0x41, 0x72, 0x65, 0x61, 0x12, 0x1d, 0x2e, 0x61, 0x72,
	0x65, 0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x53, 0x71,
	0x75, 0x61, 0x72, 0x65, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x1a, 0x1a, 0x2e, 0x61, 0x72, 0x65,
	0x61, 0x5f, 0x63, 0x61, 0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x2e, 0x41, 0x72, 0x65,
	0x61, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x00, 0x42, 0x1e, 0x5a, 0x1c, 0x67, 0x72, 0x70, 0x63,
	0x2d, 0x67, 0x6f, 0x2d, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x61, 0x72, 0x65, 0x61, 0x5f, 0x63, 0x61,
	0x6c, 0x63, 0x75, 0x6c, 0x61, 0x74, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_area_calculator_area_calculator_proto_rawDescOnce sync.Once
	file_area_calculator_area_calculator_proto_rawDescData = file_area_calculator_area_calculator_proto_rawDesc
)

func file_area_calculator_area_calculator_proto_rawDescGZIP() []byte {
	file_area_calculator_area_calculator_proto_rawDescOnce.Do(func() {
		file_area_calculator_area_calculator_proto_rawDescData = protoimpl.X.CompressGZIP(file_area_calculator_area_calculator_proto_rawDescData)
	})
	return file_area_calculator_area_calculator_proto_rawDescData
}

var file_area_calculator_area_calculator_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_area_calculator_area_calculator_proto_goTypes = []interface{}{
	(*TriangleParams)(nil),  // 0: area_calculator.TriangleParams
	(*RectangleParams)(nil), // 1: area_calculator.RectangleParams
	(*RhombusParams)(nil),   // 2: area_calculator.RhombusParams
	(*SquareParams)(nil),    // 3: area_calculator.SquareParams
	(*AreaReply)(nil),       // 4: area_calculator.AreaReply
}
var file_area_calculator_area_calculator_proto_depIdxs = []int32{
	0, // 0: area_calculator.AreaCalculator.TriangleArea:input_type -> area_calculator.TriangleParams
	1, // 1: area_calculator.AreaCalculator.RectangleArea:input_type -> area_calculator.RectangleParams
	2, // 2: area_calculator.AreaCalculator.RhombusArea:input_type -> area_calculator.RhombusParams
	3, // 3: area_calculator.AreaCalculator.SquareArea:input_type -> area_calculator.SquareParams
	4, // 4: area_calculator.AreaCalculator.TriangleArea:output_type -> area_calculator.AreaReply
	4, // 5: area_calculator.AreaCalculator.RectangleArea:output_type -> area_calculator.AreaReply
	4, // 6: area_calculator.AreaCalculator.RhombusArea:output_type -> area_calculator.AreaReply
	4, // 7: area_calculator.AreaCalculator.SquareArea:output_type -> area_calculator.AreaReply
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_area_calculator_area_calculator_proto_init() }
func file_area_calculator_area_calculator_proto_init() {
	if File_area_calculator_area_calculator_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_area_calculator_area_calculator_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TriangleParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_area_calculator_area_calculator_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RectangleParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_area_calculator_area_calculator_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RhombusParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_area_calculator_area_calculator_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SquareParams); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_area_calculator_area_calculator_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AreaReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_area_calculator_area_calculator_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_area_calculator_area_calculator_proto_goTypes,
		DependencyIndexes: file_area_calculator_area_calculator_proto_depIdxs,
		MessageInfos:      file_area_calculator_area_calculator_proto_msgTypes,
	}.Build()
	File_area_calculator_area_calculator_proto = out.File
	file_area_calculator_area_calculator_proto_rawDesc = nil
	file_area_calculator_area_calculator_proto_goTypes = nil
	file_area_calculator_area_calculator_proto_depIdxs = nil
}
